// Run `make gen` from the root of the repository to regenerate this file.
// Code generated by 'guts'. DO NOT EDIT.

// From model/attendance.go
export interface Attendance {
    readonly id: string;
    readonly address: string;
    readonly created_at: string;
    readonly metaverse: MetaverseType;
    readonly location: string;
    readonly entrance_status: EntranceStatusType;
}

// From model/attendance.go
export type EntranceStatusType = "ENTER" | "EXIT";

// From model/attendance.go
export type MetaverseType = "dcl" | "hyperfy" | "irl";


